# Generated by Django 5.2.8 on 2025-11-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_id', models.CharField(max_length=50, unique=True, verbose_name='ID пациента')),
                ('encrypted_name', models.TextField(verbose_name='Зашифрованное имя пациента')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Диагноз')),
                ('icd10_codes', models.TextField(blank=True, verbose_name='Коды МКБ-10')),
                ('urgency_level', models.IntegerField(default=4, verbose_name='Уровень срочности (1-4)')),
                ('clinical_route', models.JSONField(default=dict, verbose_name='Клинический маршрут')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['urgency_level', '-created_at'],
            },
        ),
    ]
