# Generated by Django 5.2.8 on 2025-11-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hilling_doc',
            field=models.CharField(blank=True, max_length=50, verbose_name='Лечащий врач'),
        ),
    ]
