# Generated by Django 5.2.8 on 2025-11-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_patient_hilling_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='visits_data',
            field=models.JSONField(default=list, help_text='Список визитов в формате JSON', verbose_name='Данные визитов'),
        ),
    ]
