# Generated by Django 5.2.8 on 2025-11-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_patient_visits_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='visits_data',
            field=models.JSONField(blank=True, default=list, verbose_name='Данные визитов'),
        ),
    ]
