# Generated by Django 5.2.8 on 2025-11-16 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_patient_visits_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-emergency_criteria', 'urgency_level', '-created_at']},
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_criteria',
            field=models.IntegerField(default=50, help_text='Оценка неотложности состояния пациента по шкале от 1 до 100', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Критерий неотложности (1-100)'),
        ),
    ]
