# Generated by Django 5.2.8 on 2025-11-15 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название отделения')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код отделения')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
            },
        ),
        migrations.CreateModel(
            name='MedicalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('therapist', 'Терапевт'), ('surgeon', 'Хирург'), ('cardiologist', 'Кардиолог'), ('neurologist', 'Невролог'), ('traumatologist', 'Травматолог'), ('pediatrician', 'Педиатр')], max_length=50, verbose_name='Специализация')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='Номер лицензии')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department', verbose_name='Отделение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Медицинский работник',
                'verbose_name_plural': 'Медицинские работники',
            },
        ),
    ]
